#!/bin/sh

# Generate host keys here. This will have some benifits:
# - Speed up first boot time ever so slightly.
# - SSH from a SUT to a VM without trash VM's old host key
#   because of the constant host key.
# It does however mean that keys are not unique across installations,
# shouldn't be an issue for our use case though.

sudo mkdir -m 0775 -p etc/ssh
for a in rsa ecdsa ed25519 dsa
do
  sudo ssh-keygen -f etc/ssh/ssh_host_${a}_key -N "" -t ${a}
done
